// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5SzBXUzBx1a_9r2Q9ZiWT_6UlHT0EHc0',
    appId: '1:675486380695:web:7588f70043cff95a4d2fd2',
    messagingSenderId: '675486380695',
    projectId: 'mini-project-53b3e',
    authDomain: 'mini-project-53b3e.firebaseapp.com',
    storageBucket: 'mini-project-53b3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQqq2MPvfKuXyihMJgoAXlRyhUYCF0sQ',
    appId: '1:675486380695:android:7c4fa881287d15c54d2fd2',
    messagingSenderId: '675486380695',
    projectId: 'mini-project-53b3e',
    storageBucket: 'mini-project-53b3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZN2uv1v91X6HB1_kqIFqi4arQ2r5Nusk',
    appId: '1:675486380695:ios:b0715f3e43aabe094d2fd2',
    messagingSenderId: '675486380695',
    projectId: 'mini-project-53b3e',
    storageBucket: 'mini-project-53b3e.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZN2uv1v91X6HB1_kqIFqi4arQ2r5Nusk',
    appId: '1:675486380695:ios:b0715f3e43aabe094d2fd2',
    messagingSenderId: '675486380695',
    projectId: 'mini-project-53b3e',
    storageBucket: 'mini-project-53b3e.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5SzBXUzBx1a_9r2Q9ZiWT_6UlHT0EHc0',
    appId: '1:675486380695:web:ba5c40a808626cc14d2fd2',
    messagingSenderId: '675486380695',
    projectId: 'mini-project-53b3e',
    authDomain: 'mini-project-53b3e.firebaseapp.com',
    storageBucket: 'mini-project-53b3e.firebasestorage.app',
  );
}
